"""Add field for restriction enzyme recognition sites to avoid

Revision ID: 10f7c5617dc1
Revises: f9dffe33009b
Create Date: 2025-04-03 15:18:42.402061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10f7c5617dc1'
down_revision: Union[str, None] = 'f9dffe33009b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('restriction_sites', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'restriction_sites')
    # ### end Alembic commands ###
