"""Add input and output profiles

Revision ID: 2357a925dd39
Revises: 20cadbeedf03
Create Date: 2024-11-06 15:25:49.320940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2357a925dd39'
down_revision: Union[str, None] = '20cadbeedf03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tuned_sequences', sa.Column('input_profiles', sa.JSON(), nullable=False))
    op.add_column('tuned_sequences', sa.Column('output_profiles', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tuned_sequences', 'output_profiles')
    op.drop_column('tuned_sequences', 'input_profiles')
    # ### end Alembic commands ###
