"""Add contact_consent field

Revision ID: 30e322fe869c
Revises: 5888fd8c35af
Create Date: 2024-11-25 09:58:42.214858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30e322fe869c'
down_revision: Union[str, None] = '5888fd8c35af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contact_consent', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'contact_consent')
    # ### end Alembic commands ###
