"""Add source for codon tables

Revision ID: 491d1d1528f8
Revises: 532361cba5db
Create Date: 2024-12-08 15:31:51.247328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '491d1d1528f8'
down_revision: Union[str, None] = '532361cba5db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codon_tables', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('codon_tables', 'source')
    # ### end Alembic commands ###
