"""Add rsa_threshold for new mode and set some fields as optional

Revision ID: 4f2198ccfb0c
Revises: 00fc1416fa43
Create Date: 2025-04-15 15:48:23.171856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f2198ccfb0c'
down_revision: Union[str, None] = '00fc1416fa43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('rsa_threshold', sa.Float(), nullable=True))
    op.alter_column('tuned_sequences', 'identity_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('tuned_sequences', 'input_profiles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tuned_sequences', 'input_profiles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('tuned_sequences', 'identity_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('results', 'rsa_threshold')
    # ### end Alembic commands ###
