"""First tables

Revision ID: 5888fd8c35af
Revises: 
Create Date: 2024-11-20 09:04:59.099343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5888fd8c35af'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('codon_tables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('organism', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', 'organism')
    )
    op.create_table('codon_translations',
    sa.Column('codon_table_id', sa.UUID(), nullable=False),
    sa.Column('codon', sa.String(length=3), nullable=False),
    sa.Column('anticodon', sa.String(length=3), nullable=False),
    sa.Column('amino_acid', sa.String(length=3), nullable=False),
    sa.Column('trna_gcn', sa.Float(), nullable=False),
    sa.Column('wobble_codon', sa.String(length=3), nullable=False),
    sa.Column('wobble_rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['codon_table_id'], ['codon_tables.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('codon_table_id', 'codon')
    )
    op.create_table('results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('host_codon_table_id', sa.UUID(), nullable=False),
    sa.Column('sequences_native_codon_tables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('slow_speed_threshold', sa.Float(), nullable=False),
    sa.Column('conservation_threshold', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['host_codon_table_id'], ['codon_tables.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tuned_sequences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('identity_percentage', sa.Float(), nullable=False),
    sa.Column('input_profiles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_profiles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tuned_sequences')
    op.drop_table('results')
    op.drop_table('codon_translations')
    op.drop_table('codon_tables')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
