"""Remove rsa_threshold

Revision ID: 76cedc91fe0d
Revises: d8809cfde9bd
Create Date: 2025-04-23 10:20:27.639210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76cedc91fe0d'
down_revision: Union[str, None] = 'd8809cfde9bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
