"""Unique constraint with postgresql_nulls_not_distinct

Revision ID: 771c37e47da9
Revises: 491d1d1528f8
Create Date: 2024-12-09 20:05:23.948858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '771c37e47da9'
down_revision: Union[str, None] = '491d1d1528f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('codon_tables_user_id_name_organism_key', 'codon_tables', type_='unique')
    op.create_unique_constraint('uq_codon_table_with_nulls_not_distinct', 'codon_tables', ['user_id', 'name', 'organism'], postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_codon_table_with_nulls_not_distinct', 'codon_tables', type_='unique')
    op.create_unique_constraint('codon_tables_user_id_name_organism_key', 'codon_tables', ['user_id', 'name', 'organism'])
    # ### end Alembic commands ###
