"""Add table for last web scraping

Revision ID: e809b14407e7
Revises: 771c37e47da9
Create Date: 2025-01-21 16:06:37.551704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e809b14407e7'
down_revision: Union[str, None] = '771c37e47da9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_web_scraping',
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('release', sa.String(), nullable=False),
    sa.Column('scraping_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('source', 'release')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('last_web_scraping')
    # ### end Alembic commands ###
