"""Add fields for five prime region tuning

Revision ID: f9dffe33009b
Revises: 16efda003b25
Create Date: 2025-03-06 14:57:00.524060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9dffe33009b'
down_revision: Union[str, None] = '16efda003b25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('five_prime_region_tuning', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('run_infos', sa.Column('five_prime_region_tuning_mode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_infos', 'five_prime_region_tuning_mode')
    op.drop_column('results', 'five_prime_region_tuning')
    # ### end Alembic commands ###
