@startuml use_cases
left to right direction
skinparam dpi 200

actor LoggedUser
actor Admin
actor Member
actor GuestUser

usecase "Add/edit/remove codon tables" as u1
usecase "Run tuning" as u2
usecase "Read result" as u3
usecase "Download result" as u4
usecase "Access to previous results" as u5
usecase "Edit/remove users" as u6
usecase "Access usage statistics" as u7

Admin --> LoggedUser #line:MediumPurple
Member --> LoggedUser #line:MediumPurple

GuestUser --> u2 #line:LimeGreen
GuestUser --> u3 #line:LimeGreen
GuestUser --> u4 #line:LimeGreen

LoggedUser --> u1 #line:DodgerBlue
LoggedUser --> u2 #line:DodgerBlue
LoggedUser --> u3 #line:DodgerBlue
LoggedUser --> u4 #line:DodgerBlue
LoggedUser --> u5 #line:DodgerBlue

Admin --> u6 #line:Crimson
Admin --> u7 #line:Crimson
@enduml