export const CODON_TABLE_LIST = [
  {
    name: 'Arabidopsis_thaliana',
    organism: 'Arabidopsis_thaliana',
    custom: false,
  },
  { name: 'Bacillus_subtilis', organism: 'Bacillus_subtilis', custom: false },
  {
    name: 'Caenorhabditis_elegans',
    organism: 'Caenorhabditis_elegans',
    custom: false,
  },
  { name: 'Danio_rerio', organism: 'Danio_rerio', custom: false },
  {
    name: 'Drosophila_melanogaster',
    organism: 'Drosophila_melanogaster',
    custom: false,
  },
  { name: 'Escherichia_coli', organism: 'Escherichia_coli', custom: false },
  { name: 'Gallus_gallus', organism: 'Gallus_gallus', custom: false },
  { name: 'Homo_sapiens', organism: 'Homo_sapiens', custom: false },
  {
    name: 'Komagataella_pastoris',
    organism: 'Komagataella_pastoris',
    custom: false,
  },
  {
    name: 'Methanocaldococcus_jannaschii',
    organism: 'Methanocaldococcus_jannaschii',
    custom: false,
  },
  {
    name: 'Saccharomyces_cerevisiae',
    organism: 'Saccharomyces_cerevisiae',
    custom: false,
  },
  {
    name: 'Staphylococcus_aureus',
    organism: 'Staphylococcus_aureus',
    custom: false,
  },
  { name: 'Xenopus_laevis', organism: 'Xenopus_laevis', custom: false },
]

export const MODE_LABEL_MAPPING: Record<string, string> = {
  direct_mapping: 'Direct mapping',
  optimisation_and_conservation_1: 'Optimisation and conservation 1',
  optimisation_and_conservation_2: 'Optimisation and conservation 2',
}

export const BASE_CODON_TABLE = [
  { aminoAcid: 'Ala', anticodon: 'AGC', codon: 'GCU' },
  { aminoAcid: 'Ala', anticodon: 'GGC', codon: 'GCC' },
  { aminoAcid: 'Ala', anticodon: 'CGC', codon: 'GCG' },
  { aminoAcid: 'Ala', anticodon: 'UGC', codon: 'GCA' },
  { aminoAcid: 'Arg', anticodon: 'ACG', codon: 'CGU' },
  { aminoAcid: 'Arg', anticodon: 'GCG', codon: 'CGC' },
  { aminoAcid: 'Arg', anticodon: 'CCG', codon: 'CGG' },
  { aminoAcid: 'Arg', anticodon: 'UCG', codon: 'CGA' },
  { aminoAcid: 'Arg', anticodon: 'CCU', codon: 'AGG' },
  { aminoAcid: 'Arg', anticodon: 'UCU', codon: 'AGA' },
  { aminoAcid: 'Asn', anticodon: 'AUU', codon: 'AAU' },
  { aminoAcid: 'Asn', anticodon: 'GUU', codon: 'AAC' },
  { aminoAcid: 'Asp', anticodon: 'AUC', codon: 'GAU' },
  { aminoAcid: 'Asp', anticodon: 'GUC', codon: 'GAC' },
  { aminoAcid: 'Cys', anticodon: 'ACA', codon: 'UGU' },
  { aminoAcid: 'Cys', anticodon: 'GCA', codon: 'UGC' },
  { aminoAcid: 'Gln', anticodon: 'CUG', codon: 'CAG' },
  { aminoAcid: 'Gln', anticodon: 'UUG', codon: 'CAA' },
  { aminoAcid: 'Glu', anticodon: 'CUC', codon: 'GAG' },
  { aminoAcid: 'Glu', anticodon: 'UUC', codon: 'GAA' },
  { aminoAcid: 'Gly', anticodon: 'ACC', codon: 'GGU' },
  { aminoAcid: 'Gly', anticodon: 'GCC', codon: 'GGC' },
  { aminoAcid: 'Gly', anticodon: 'CCC', codon: 'GGG' },
  { aminoAcid: 'Gly', anticodon: 'UCC', codon: 'GGA' },
  { aminoAcid: 'His', anticodon: 'AUG', codon: 'CAU' },
  { aminoAcid: 'His', anticodon: 'GUG', codon: 'CAC' },
  { aminoAcid: 'Ile', anticodon: 'AAU', codon: 'AUU' },
  { aminoAcid: 'Ile', anticodon: 'GAU', codon: 'AUC' },
  { aminoAcid: 'Ile', anticodon: 'CAU', codon: 'AUA' },
  { aminoAcid: 'Leu', anticodon: 'AAG', codon: 'CUU' },
  { aminoAcid: 'Leu', anticodon: 'GAG', codon: 'CUC' },
  { aminoAcid: 'Leu', anticodon: 'CAG', codon: 'CUG' },
  { aminoAcid: 'Leu', anticodon: 'UAG', codon: 'CUA' },
  { aminoAcid: 'Leu', anticodon: 'CAA', codon: 'UUG' },
  { aminoAcid: 'Leu', anticodon: 'UAA', codon: 'UUA' },
  { aminoAcid: 'Lys', anticodon: 'CUU', codon: 'AAG' },
  { aminoAcid: 'Lys', anticodon: 'UUU', codon: 'AAA' },
  { aminoAcid: 'Met', anticodon: 'CAU', codon: 'AUG' },
  { aminoAcid: 'Phe', anticodon: 'AAA', codon: 'UUU' },
  { aminoAcid: 'Phe', anticodon: 'GAA', codon: 'UUC' },
  { aminoAcid: 'Pro', anticodon: 'AGG', codon: 'CCU' },
  { aminoAcid: 'Pro', anticodon: 'GGG', codon: 'CCC' },
  { aminoAcid: 'Pro', anticodon: 'CGG', codon: 'CCG' },
  { aminoAcid: 'Pro', anticodon: 'UGG', codon: 'CCA' },
  { aminoAcid: 'Ser', anticodon: 'AGA', codon: 'UCU' },
  { aminoAcid: 'Ser', anticodon: 'GGA', codon: 'UCC' },
  { aminoAcid: 'Ser', anticodon: 'CGA', codon: 'UCG' },
  { aminoAcid: 'Ser', anticodon: 'UGA', codon: 'UCA' },
  { aminoAcid: 'Ser', anticodon: 'ACU', codon: 'AGU' },
  { aminoAcid: 'Ser', anticodon: 'GCU', codon: 'AGC' },
  { aminoAcid: 'Thr', anticodon: 'AGU', codon: 'ACU' },
  { aminoAcid: 'Thr', anticodon: 'GGU', codon: 'ACC' },
  { aminoAcid: 'Thr', anticodon: 'CGU', codon: 'ACG' },
  { aminoAcid: 'Thr', anticodon: 'UGU', codon: 'ACA' },
  { aminoAcid: 'Trp', anticodon: 'CCA', codon: 'UGG' },
  { aminoAcid: 'Tyr', anticodon: 'AUA', codon: 'UAU' },
  { aminoAcid: 'Tyr', anticodon: 'GUA', codon: 'UAC' },
  { aminoAcid: 'Val', anticodon: 'AAC', codon: 'GUU' },
  { aminoAcid: 'Val', anticodon: 'GAC', codon: 'GUC' },
  { aminoAcid: 'Val', anticodon: 'CAC', codon: 'GUG' },
  { aminoAcid: 'Val', anticodon: 'UAC', codon: 'GUA' },
]

export const CODON_MAPPING = Object.fromEntries(
  BASE_CODON_TABLE.map(e => [e.codon, e]),
)
